### ISSUE TITLE
installation synology

### ISSUE THREAD

**Issue by tinopfl** [ChriD/node-raumserver#28]
Hi,

I tried a a installation on my synology, unfortunatly there is only Node v4 available.

During the installation I got some warnings about the node version, when I try to start I got the following:

tino@DiskStation:/usr/local/rf$ node node_modules/node-raumserver/test.js
/usr/local/rf/node_modules/node-raumserver/lib/lib.raumserver.js:27
    createLogger(_logLevel = 2, _path = "./logs")
                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/rf/node_modules/node-raumserver/test.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Is the node version too old for your package?

Best Regards, Tino.

**Comment by ChriD** [comment]
Yes. Node 4.0 is way too old

```
Please use with node version 7.x or above
For Version lower than 7.6.0 the --harmony-async-await parameter has to be used
```

Do you have Docker on your NAS?
What about the docker image? This is up to date.
https://hub.docker.com/_/node/
