### ISSUE TITLE
node-raumserver can not change volume but old windows raumserver is working

### ISSUE THREAD

**Issue by holli73** [ChriD/node-raumserver#39]
hello,

for my new app i'm using the the new node way - but i do have an issue with some task - they do not work as expected - once i restart the rf device the node app is working again - but why is not working when the old raumserver on windows doesn't suffer from this error?

f.ex. - just setting the volume up returns:

`{"requestUrl":"/raumserver/controller/setVolume?id=Kueche&value=17","action":"setVolume","error":true,"msg":"Action was rejected","data":{"errorMessage":"Error: connect ECONNREFUSED 192.168.251.200:56421","errorData":null}}`

the get renderstate for this room shows:

```
{
requestUrl :  "/raumserver/controller/getRendererState?id=Kueche&_=1503220418150",
action :  "getRendererState",
error :  false,
msg :  "",
data : [
{
mute :  0,
InstanceID :  0,
CurrentTrackMetaData :  "",
CurrentRecordQualityMode :  "NOT_IMPLEMENTED",
AbsoluteTimePosition :  "00:00:00",
SecondsUntilSleep :  "0",
CurrentTrack :  "1",
AVTransportURIMetaData :  "",
PossiblePlaybackStorageMedia :  "NETWORK",
TransportPlaySpeed :  "1",
CurrentTrackDuration :  "00:00:00",
PossibleRecordQualityModes :  "NOT_IMPLEMENTED",
TransportError :  "",
PossibleRecordStorageMedia :  "NONE",
AVTransportURI :  "dlna-playcontainer://uuid%3A2fe2f1b7-8578-47c7-9a59-f60706cc265d?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&cid=0%2FPlaylists%2FMyPlaylists%2FOE3&md=0&fii=0",
RelativeTimePosition :  "00:00:00",
RelativeCounterPosition :  "1",
CurrentPlayMode :  "NORMAL",
Bitrate :  "128",
TransportState :  "PLAYING",
AbsoluteCounterPosition :  "1",
CurrentTransportActions :  "Repeat,Stop",
RoomStates :  "uuid:8d10c182-e6e5-4c54-817e-9313877877f7=STOPPED",
ContentType :  "MP3",
NumberOfTracks :  "1",
SleepTimerActive :  "0",
TransportStatus :  "buffer underrun in Kueche",
CurrentTrackURI :  "http://mp3stream7.apasf.apa.at:8000",
RoomVolumes :  "uuid:8d10c182-e6e5-4c54-817e-9313877877f7=16",
Volume :  "16",
Mute :  "0",
RoomMutes :  "uuid:8d10c182-e6e5-4c54-817e-9313877877f7=0",
rooms : [
{
roomUDN :  "uuid:8d10c182-e6e5-4c54-817e-9313877877f7",
transportState :  "STOPPED",
online :  true,
volume :  "16",
mute :  "0",
name :  "Kueche",
udn :  "uuid:8d10c182-e6e5-4c54-817e-9313877877f7",
powerState :  "ACTIVE",
renderer : [
{
udn :  "uuid:f2db5ae9-8926-4dcf-9ada-f52f2b9240b1",
name :  "Speaker Kueche"
}
]
}
],
udn :  "uuid:94A96919-D9AB-4550-A850-C24B749082CE",
mediaItem :  null,
friendlyName :  "Kueche",
host :  "192.168.251.200",
manufacturer :  "Raumfeld GmbH",
modelNumber :  "2"
}
]
}

```

any idea?

thanks
holli

**Comment by ChriD** [comment]
Not sure about that. I do not suffer this issue. 

On which device does the raumserver run?

BTW: You have a buffer underun?!
`TransportStatus :  "buffer underrun in Kueche",`

**Comment by holli73** [comment]
hello,

the raumserver runs on a x64 linux (ubuntu 16.04.3) (direct on this vm host)
the old raumserver runs on the same linux box in a x32 win10 vm on the same box.

the only ways to solve this is by restarting the rf device.

TransportStatus : "buffer underrun in Kueche"

but the device was playing fine the radio stream and i was able to pause/vol+- through the old but not the noderfapi.

thanks
holli

**Comment by ChriD** [comment]
When does it stop working? Any idea? Maybe if the device comes up from the sleep mode? 
Can you please give me some more information. The ECONRESET error pops up if the UPNP subscription actions can not communicate with the upnp device.

**Comment by holli73** [comment]
hello,

this is within the log

```
holli@obelix:~/BUILD/raumserver/npm-install/node_modules/node-raumserver/logs$ cat app.2017-09-10-0707.log
2017-09-10T07:07:09.897Z - verbose: [Raumserver] Request received: GET /raumserver/controller/setVolume?id=Kueche&value=17
2017-09-10T07:07:09.898Z - debug: [Raumserver] Request to raumserver recognized: /raumserver/controller/setVolume?id=Kueche&value=17
2017-09-10T07:07:09.898Z - debug: [Raumserver] Handle action 'setVolume' with query: {"id":"Kueche","value":"17"}
2017-09-10T07:07:09.898Z - debug: [DeviceManager] Trying to get virtual media renderer for id or (child)name : Kueche
2017-09-10T07:07:09.898Z - debug: [DeviceManager] Trying to get media renderer for id name : Kueche
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:137ea741-1abf-4acb-b40e-f159c9bda2e1
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:431961ef-c07e-4013-8cf9-7d359c4f82a6
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:7abc79a3-910d-410e-b93b-0621833e6755
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:a2bc2f63-5ceb-48fc-af92-d4a7fa33e547
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:c80fefa9-84dd-4282-8977-4f9976a25872
2017-09-10T07:07:09.898Z - debug: [ZoneManager] Get room information object for: uuid:f2db5ae9-8926-4dcf-9ada-f52f2b9240b1
2017-09-10T07:07:09.898Z - debug: [DeviceManager] Media renderer for id : Kueche found
2017-09-10T07:07:09.898Z - debug: [Request.setVolume] Calling action 'setVolume' for renderer Kueche
2017-09-10T07:07:09.898Z - debug: [MediaRenderer|Kueche] Set volume to 17 on room Kueche
2017-09-10T07:07:09.898Z - debug: [MediaRenderer|Kueche] Call SetVolume from Kueche
2017-09-10T07:07:09.899Z - error: [MediaRenderer|Kueche] SetVolume on Kueche failed with params: {"Channel":"Master","DesiredVolume":17} Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:09.899Z - error: [Request.setVolume] Exception thrown:  Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:09.900Z - error: [Request.setVolume] Some renderers had exceptions:  Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:09.900Z - error: [Raumserver] Request was rejected:  errorMessage=Error: connect ECONNREFUSED 192.168.251.200:56421, errorData=null
2017-09-10T07:07:16.433Z - verbose: [Raumserver] Request received: GET /raumserver/controller/getRendererState?id=Kueche
2017-09-10T07:07:16.434Z - debug: [Raumserver] Request to raumserver recognized: /raumserver/controller/getRendererState?id=Kueche
2017-09-10T07:07:16.434Z - debug: [Raumserver] Handle action 'getRendererState' with query: {"id":"Kueche"}
2017-09-10T07:07:16.434Z - debug: [DeviceManager] Trying to get virtual media renderer for id or (child)name : Kueche
2017-09-10T07:07:16.434Z - debug: [DeviceManager] Trying to get media renderer for id name : Kueche
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:137ea741-1abf-4acb-b40e-f159c9bda2e1
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:431961ef-c07e-4013-8cf9-7d359c4f82a6
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:7abc79a3-910d-410e-b93b-0621833e6755
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:a2bc2f63-5ceb-48fc-af92-d4a7fa33e547
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:c80fefa9-84dd-4282-8977-4f9976a25872
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:f2db5ae9-8926-4dcf-9ada-f52f2b9240b1
2017-09-10T07:07:16.434Z - debug: [DeviceManager] Media renderer for id : Kueche found
2017-09-10T07:07:16.434Z - debug: [Request.getRendererState] No updateId given for action 'getRendererState'. Using direct execution
2017-09-10T07:07:16.434Z - debug: [Request.getRendererState] Adding response header for request 'getRendererState' -> updateId : 179297
2017-09-10T07:07:16.434Z - debug: [ZoneManager] Get room information object for: uuid:8d10c182-e6e5-4c54-817e-9313877877f7
2017-09-10T07:07:16.434Z - debug: [Request.getRendererState] Request was accepted and was successfully executed
2017-09-10T07:07:22.411Z - verbose: [Raumserver] Request received: GET /raumserver/controller/setVolume?id=Kueche&value=17
2017-09-10T07:07:22.411Z - debug: [Raumserver] Request to raumserver recognized: /raumserver/controller/setVolume?id=Kueche&value=17
2017-09-10T07:07:22.411Z - debug: [Raumserver] Handle action 'setVolume' with query: {"id":"Kueche","value":"17"}
2017-09-10T07:07:22.411Z - debug: [DeviceManager] Trying to get virtual media renderer for id or (child)name : Kueche
2017-09-10T07:07:22.411Z - debug: [DeviceManager] Trying to get media renderer for id name : Kueche
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:137ea741-1abf-4acb-b40e-f159c9bda2e1
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:431961ef-c07e-4013-8cf9-7d359c4f82a6
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:7abc79a3-910d-410e-b93b-0621833e6755
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:a2bc2f63-5ceb-48fc-af92-d4a7fa33e547
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:c80fefa9-84dd-4282-8977-4f9976a25872
2017-09-10T07:07:22.411Z - debug: [ZoneManager] Get room information object for: uuid:f2db5ae9-8926-4dcf-9ada-f52f2b9240b1
2017-09-10T07:07:22.412Z - debug: [DeviceManager] Media renderer for id : Kueche found
2017-09-10T07:07:22.412Z - debug: [Request.setVolume] Calling action 'setVolume' for renderer Kueche
2017-09-10T07:07:22.412Z - debug: [MediaRenderer|Kueche] Set volume to 17 on room Kueche
2017-09-10T07:07:22.412Z - debug: [MediaRenderer|Kueche] Call SetVolume from Kueche
2017-09-10T07:07:22.413Z - error: [MediaRenderer|Kueche] SetVolume on Kueche failed with params: {"Channel":"Master","DesiredVolume":17} Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:22.413Z - error: [Request.setVolume] Exception thrown:  Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:22.413Z - error: [Request.setVolume] Some renderers had exceptions:  Error: connect ECONNREFUSED 192.168.251.200:56421
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
2017-09-10T07:07:22.413Z - error: [Raumserver] Request was rejected:  errorMessage=Error: connect ECONNREFUSED 192.168.251.200:56421, errorData=null
2017-09-10T07:07:29.065Z - verbose: [Raumserver] Request received: GET /raumserver/controller/getRendererState?id=Kueche
2017-09-10T07:07:29.065Z - debug: [Raumserver] Request to raumserver recognized: /raumserver/controller/getRendererState?id=Kueche
2017-09-10T07:07:29.065Z - debug: [Raumserver] Handle action 'getRendererState' with query: {"id":"Kueche"}
2017-09-10T07:07:29.065Z - debug: [DeviceManager] Trying to get virtual media renderer for id or (child)name : Kueche
2017-09-10T07:07:29.065Z - debug: [DeviceManager] Trying to get media renderer for id name : Kueche
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:137ea741-1abf-4acb-b40e-f159c9bda2e1
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:431961ef-c07e-4013-8cf9-7d359c4f82a6
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:7abc79a3-910d-410e-b93b-0621833e6755
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:a2bc2f63-5ceb-48fc-af92-d4a7fa33e547
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:c80fefa9-84dd-4282-8977-4f9976a25872
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:f2db5ae9-8926-4dcf-9ada-f52f2b9240b1
2017-09-10T07:07:29.065Z - debug: [DeviceManager] Media renderer for id : Kueche found
2017-09-10T07:07:29.065Z - debug: [Request.getRendererState] No updateId given for action 'getRendererState'. Using direct execution
2017-09-10T07:07:29.065Z - debug: [Request.getRendererState] Adding response header for request 'getRendererState' -> updateId : 179297
2017-09-10T07:07:29.065Z - debug: [ZoneManager] Get room information object for: uuid:8d10c182-e6e5-4c54-817e-9313877877f7
2017-09-10T07:07:29.065Z - debug: [Request.getRendererState] Request was accepted and was successfully executed

```

**Comment by gahujipo** [comment]
I think @holli73 is having the same effect as me in https://github.com/ChriD/node-raumserver/issues/37 even the log entries are similar to mine.

**Comment by ChriD** [comment]
Hmm. Holly does not mention that he is rebooting the host.

**Comment by gahujipo** [comment]
I'm not sure if @holli73 has this problem when he restarts the Raumfeld device:
> once i restart the rf device the node app is working again - but why is not working when the old raumserver on windows doesn't suffer from this error

**Comment by Adrian01** [comment]
I have the same Problem, restart the node-raumserver (del_test.js) and it works but the Reason i dont know.

**Comment by holli73** [comment]
hello,

i did not re-start the rf-expand on purpose - but i can not tell if it might rebooted on its own - or one of the latest update + reboot caused the node-rf server to fail - but i still do not understand why the old windows api works and if the port changed the node-rf not trying to get the new port?

thanks
holli

**Comment by ChriD** [comment]
May be fixed with latest release.
