### ISSUE TITLE
async fadeToVolume... SyntaxError: Unexpected identifier starting node-raumserver

### ISSUE THREAD

**Issue by rwitkamp** [ChriD/node-raumserver#41]
After a full Fedora 25 system re-install I'm trying to re-install node-raumserver. After installing npm, nodejs and node-raumserver I got this error starting node-raumserver. Any idea how to solve this?

[root@area51 ~]# node node_modules/node-raumserver/raumserver.js
WARNING: No configurations found in configuration directory:/root/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/root/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.raumfeld.js:37
    async fadeToVolume(_desiredVolume, _duration = 2000)
          ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:13:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[root@area51 ~]#

**Comment by rwitkamp** [comment]
Sorry, it was the NodeJs version that should be >8   Upgraded NodeJs and all is working!
