### ISSUE TITLE
Problems by installing on Raspi

### ISSUE THREAD

**Issue by tomtaa** [ChriD/node-raumserver#44]
Hallo,

ich habe versucht, den node-raumserver auf meinen Raspi3 zu installieren.
Dazu bin ich der Anleitung auf Issue #12 gefolgt.
Beim Starten erhalte ich jedoch eine Fehlermeldung:

pi@raspberrypi:~/node_modules/node-raumserver $ node raumserver.js
/home/pi/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.raumfeld.js:37
    async fadeToVolume(_desiredVolume, _duration = 2000)
          ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:13:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

Leider habe ich nicht die Kenntnisse, damit was anzufangen. 
Was mache ich falsch?
Nur zur Vollständigkeit- denke aber, das ist noch nicht wichtig: Habe einen Raumfeld Connector als Host und ein paar One S.

**Comment by ChriD** [comment]
Du benutzt einen alten nodeJs der den "async" befehl noch nicht kann --> nodeJs updated!

**Comment by tomtaa** [comment]
Das war es.  Hätte ich auch selber drauf kommen können. Jetzt läuft es.
Besten Dank. - sowohl für die Hilfe als auch für das Tool.
