### ISSUE TITLE
Renderer lost after power failure

### ISSUE THREAD

**Issue by greentux** [ChriD/node-raumserver#58]
After power lost and power back of the renderer (Raumfeld S) the renderer will not be found.
Works fine after restart the node-raumserver.
Any possibility to fix that?

**Comment by ChriD** [comment]
This problem should have been fixed already in a new kernel.
What kernel version do you have?

**Comment by greentux** [comment]
info: [Raumserver] Welcome to raumserver v0.1.4 (raumkernel v1.2.21)
info: [Raumserver] eth0 192.168.179.11
just updated... will check.

**Comment by greentux** [comment]
error: [MediaRenderer|Speaker One] EnterManualStandby on Speaker One failed with params: {} Error: connect ECONNREFUSED 192.168.179.26:56285
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
error: [Request.enterManualStandby] Error: connect ECONNREFUSED 192.168.179.26:56285

**Comment by greentux** [comment]
anything I can do/test/log?

**Comment by ChriD** [comment]
I'm very busy at the moment. It will take a while until i can investigate this

**Comment by gahujipo** [comment]
I can describe you what happens in my use case. Most of the times the node-raumserver rediscovers all RF devices as expected, but after some days sometimes it doesn't find the devices automatically without restarting node-raumserver even after some hours (powering up RF devices in the morning - testing in the evening). I think none of the commands in that case work.

**Comment by greentux** [comment]
checked that again.
- ONE S is playing radio...
`wget http://localhost:8080/raumserver/controller/toggleMute`
-> radio mutes.
`{"requestUrl":"/raumserver/controller/toggleMute","action":"toggleMute","error":false,"msg":"","data":{"udn":"uuid:16d59da6-e877-4ce2-a9e7-905a4edcd485"}}`
- 5 times again, worked fine.
- Removing power, connect again, ONE S restarts.
- And plays radio again.
`wget http://localhost:8080/raumserver/controller/toggleMute`
-> nothing happens, radio plays...
`{"requestUrl":"/raumserver/controller/toggleMute","action":"toggleMute","error":true,"msg":"Action was rejected","data":{"errorMessage":"Error: connect ECONNREFUSED 192.168.179.26:57612","errorData":null}}`
- IP adress is static, fine.
I will check the log...

**Comment by greentux** [comment]
last working log
`2018-04-10T18:27:32.527Z - error: [MediaDataConverter] Error converting media item: "" TypeError: Cannot read property 'toLowerCase' of null
    at Raumkernel.convertContainer (/root/raumnode/node_modules/node-raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:110:32)
    at /root/raumnode/node_modules/node-raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:71:65
    at Parser.<anonymous> (/root/raumnode/node_modules/node-raumserver/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (/root/raumnode/node_modules/node-raumserver/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/root/raumnode/node_modules/node-raumserver/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/root/raumnode/node_modules/node-raumserver/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/root/raumnode/node_modules/node-raumserver/node_modules/sax/lib/sax.js:903:7)
    at SAXParser.write (/root/raumnode/node_modules/node-raumserver/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/root/raumnode/node_modules/node-raumserver/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/root/raumnode/node_modules/node-raumserver/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/root/raumnode/node_modules/node-raumserver/node_modules/xml2js/lib/parser.js:354:19)
    at /root/raumnode/node_modules/node-raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:25:13
    at Raumkernel.convertXMLToMediaList (/root/raumnode/node_modules/node-raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:22:16)
    at /root/raumnode/node_modules/node-raumserver/node_modules/node-raumkernel/lib/lib.manager.mediaListManager.js:286:40
`
followed by
`2018-04-10T18:28:50.314Z - error:  Error: connect ECONNREFUSED 192.168.179.26:51968
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
`
and
`2018-04-10T18:30:03.698Z - error: [MediaRenderer|One] GetMute on One failed with params: {"Channel":"Master"} Error: connect ECONNREFUSED 192.168.179.26:57612
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
2018-04-10T18:30:03.699Z - error: [Request.toggleMute] Exception thrown:  Error: connect ECONNREFUSED 192.168.179.26:57612
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
2018-04-10T18:30:03.699Z - error: [Request.toggleMute] Some renderers had exceptions:  Error: connect ECONNREFUSED 192.168.179.26:57612
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
2018-04-10T18:30:03.701Z - error: [Raumserver] Request was rejected:  errorMessage=Error: connect ECONNREFUSED 192.168.179.26:57612, errorData=null
`
restaring the raumserver-node
`2018-04-10T18:37:26.777Z - info: [Raumserver] Welcome to raumserver v0.1.4 (raumkernel v1.2.21)
2018-04-10T18:37:26.784Z - info: [Raumserver] eth0 192.168.179.11
2018-04-10T18:37:27.069Z - info: [Raumkernel] Found raumfeld host on: 192.168.179.26
2018-04-10T18:37:30.420Z - info: [DeviceManager] Media Server added: home2: root (uuid:4d696e69-444c-164e-9d41-009c02a0444f)
2018-04-10T18:37:30.460Z - info: [DeviceManager] Virtual media renderer added: One (uuid:16d59da6-e877-4ce2-a9e7-905a4edcd485)
2018-04-10T18:37:30.479Z - info: [DeviceManager] Raumfeld Media renderer added: Speaker One (uuid:70bc786e-c068-47ff-8f63-f0af5b8d19f5)
2018-04-10T18:37:30.508Z - info: [DeviceManager] Raumfeld media server added: Raumfeld MediaServer (uuid:7380f87a-4dca-4f55-9079-7112f073b0cb)
`

**Comment by greentux** [comment]
fine, cant await, but I know. Sommerdays are not for coding :)

**Comment by erikp152** [comment]
> After power lost and power back of the renderer (Raumfeld S) the renderer will not be found.
> Works fine after restart the node-raumserver.
> Any possibility to fix that?

I've the same Problem as well, but with current Version. @ChriD Can you already suggest a solution for that problem? IMO the raumserver loses the Media renderer after a whole, so only restart repairs this. This error message as shown in the log above occurrs directly after starting via "npm start". :-(

**Comment by greentux** [comment]
is there any hope? ;)
