### ISSUE TITLE
Wake up from automatic standby Raumfeld Stero M

### ISSUE THREAD

**Issue by fschuber** [ChriD/node-raumserver#88]
System: Raumfeld Stereo M - Model number 2
Versions used:

requestUrl | "/raumserver/data/getVersion"
-- | --
action | "getVersion"
error | false
msg | ""
data |  
raumkernelLib | "1.2.22"
raumserverLib | "0.1.9"

The speakers are in automatic standby:  |  
-- | --
requestUrl | "/raumserver/controller/getRendererState"
action | "getRendererState"
error | false
msg | ""
data |  
0 |  
InstanceID | 0
AVTransportURIMetaData | ""
CurrentTrackDuration | "NOT_IMPLEMENTED"
PowerState | "AUTOMATIC_STANDBY"
AVTransportURI | ""
CurrentPlayMode | "NORMAL"
TransportState | "NO_MEDIA_PRESENT"
OwnsAudioResource | "0"
CurrentTransportActions | ""
TransportStatus | "OK"
LowDB | "0.000000"
Mute | "0"
MidDB | "0.000000"
Volume | "58"
Balance | "0"
HighDB | "0.000000"
rooms |  
0 |  
name | "Wohnzimmer"
udn | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState | "AUTOMATIC_STANDBY"
renderer |  
0 |  
udn | "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name | "Speaker Wohnzimmer"
udn | "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
mediaItem | null
friendlyName | "Speaker Wohnzimmer"
host | "192.168.178.20"
manufacturer | "Lautsprecher Teufel GmbH"
modelNumber | "2"

Try to leave standby:

  |  
-- | --
requestUrl | "/raumserver/controller/leaveStandby"
action | "leaveStandby"
error | true
msg | "Action was rejected"
data |  
errorMessage | "Error: VirtualMediaRenderer for id '' not found"
errorData | null

Thank you very much for the Raumserver!

**Comment by ChriD** [comment]
Hi,

i think you have to provide the id for the speaker

e.g.: /leaveStandby?id="Wohnzimmer"


________________________________
Von: fschuber <notifications@github.com>
Gesendet: Montag, 14. Oktober 2019 15:41
An: ChriD/node-raumserver <node-raumserver@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [ChriD/node-raumserver] Wake up from automatic standby Raumfeld Stero M (#88)


System: Raumfeld Stereo M - Model number 2
Versions used:

requestUrl      "/raumserver/data/getVersion"
action  "getVersion"
error   false
msg     ""
data
raumkernelLib   "1.2.22"
raumserverLib   "0.1.9"
The speakers are in automatic standby:
requestUrl      "/raumserver/controller/getRendererState"
action  "getRendererState"
error   false
msg     ""
data
0
InstanceID      0
AVTransportURIMetaData  ""
CurrentTrackDuration    "NOT_IMPLEMENTED"
PowerState      "AUTOMATIC_STANDBY"
AVTransportURI  ""
CurrentPlayMode "NORMAL"
TransportState  "NO_MEDIA_PRESENT"
OwnsAudioResource       "0"
CurrentTransportActions ""
TransportStatus "OK"
LowDB   "0.000000"
Mute    "0"
MidDB   "0.000000"
Volume  "58"
Balance "0"
HighDB  "0.000000"
rooms
0
name    "Wohnzimmer"
udn     "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState      "AUTOMATIC_STANDBY"
renderer
0
udn     "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name    "Speaker Wohnzimmer"
udn     "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
mediaItem       null
friendlyName    "Speaker Wohnzimmer"
host    "192.168.178.20"
manufacturer    "Lautsprecher Teufel GmbH"
modelNumber     "2"

Try to leave standby:


requestUrl      "/raumserver/controller/leaveStandby"
action  "leaveStandby"
error   true
msg     "Action was rejected"
data
errorMessage    "Error: VirtualMediaRenderer for id '' not found"
errorData       null

Thank you very much for the Raumserver!

**Comment by fschuber** [comment]
It was the same using ?id="Wohnzimmer".
I think the cause is with the source of the music I play.
I did play some music, so now my automatic_Standby is:

  |  
-- | --
requestUrl | "/raumserver/controller/getRendererState"
action | "getRendererState"
error | false
msg | ""
data |  
0 |  
Mute | 0
InstanceID | 0
RoomVolumes | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=58"
Volume | "58"
RoomMutes | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=0"
CurrentTrackMetaData | "<?xml version=\"1.0\"?>\n<DIDL-Lite xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\" xmlns:raumfeld=\"urn:schemas-raumfeld-com:meta-data/raumfeld\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dlna=\"urn:schemas-dlna-org:metadata-1-0/\" xmlns:pv=\"http://www.pv.com/pvns/\" lang=\"en\">\n  <item parentID=\"0/Favorites/RecentlyPlayed\" id=\"0/Favorites/RecentlyPlayed/527\" restricted=\"1\" refID=\"0/SoundCloud/DirectAccess/Track/t618985140\">\n    <raumfeld:name>Track</raumfeld:name>\n    <upnp:class>object.item.audioItem.musicTrack</upnp:class>\n    <raumfeld:section>SoundCloud</raumfeld:section>\n    <dc:title>Haszcara (feat. Tolztoy) Nein</dc:title>\n    <upnp:albumArtURI dlna:profileID=\"JPEG_TN\">http://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&amp;service=SoundCloud</upnp:albumArtURI>\n    <res protocolInfo=\"soundcloud-track-href:*:audio/soundcloud-track:*\" duration=\"0:02:55.000\">https://api-partners.soundcloud.com/tracks/soundcloud:tracks:618985140/play?anonymous_id=12a3415a-b765-4a7d-98d4-38ce923eacc6&amp;client_id=3f1da551d8578cf5985a97655011c482</res>\n    <upnp:artist>RapidGaming iTnerz</upnp:artist>\n    <dc:creator>RapidGaming iTnerz</dc:creator>\n    <raumfeld:likedOnMusicService>false</raumfeld:likedOnMusicService>\n  </item>\n</DIDL-Lite>\n"
CurrentRecordQualityMode | "NOT_IMPLEMENTED"
AbsoluteTimePosition | "00:00:00"
SecondsUntilSleep | "0"
CurrentTrack | "1"
AVTransportURIMetaData | "<?xml version=\"1.0\"?>\n<DIDL-Lite xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dlna=\"urn:schemas-dlna-org:metadata-1-0/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:raumfeld=\"urn:schemas-raumfeld-com:meta-data/raumfeld\" xmlns:pv=\"http://www.pv.com/pvns/\"><item parentID=\"0/Favorites/RecentlyPlayed\" refID=\"0/SoundCloud/DirectAccess/Track/t618985140\" id=\"0/Favorites/RecentlyPlayed/527\" restricted=\"1\"><raumfeld:section>SoundCloud</raumfeld:section><dc:title>Haszcara (feat. Tolztoy) Nein</dc:title><upnp:albumArtURI>http://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&amp;service=SoundCloud</upnp:albumArtURI><raumfeld:name>Track</raumfeld:name><upnp:class>object.item.audioItem.musicTrack</upnp:class><upnp:artist>RapidGaming iTnerz</upnp:artist><raumfeld:duration>175</raumfeld:duration></item></DIDL-Lite>\n"
PossiblePlaybackStorageMedia | "NETWORK"
TransportPlaySpeed | "1"
CurrentTrackDuration | "00:02:55"
PossibleRecordQualityModes | "NOT_IMPLEMENTED"
Bitrate | "128"
PossibleRecordStorageMedia | "NONE"
AVTransportURI | "dlna-playsingle://uuid%3A63d8bd10-ce01-4113-823c-49897c0eacc7?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&iid=0%2FFavorites%2FRecentlyPlayed%2F527"
RelativeTimePosition | "00:00:00"
RelativeCounterPosition | "1"
CurrentPlayMode | "NORMAL"
TransportState | "STOPPED"
AbsoluteCounterPosition | "1"
CurrentTransportActions | "Play,Previous,Repeat,Seek"
RoomStates | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=STOPPED"
ContentType | "MP3"
NumberOfTracks | "1"
SleepTimerActive | "0"
TransportStatus | "OK"
CurrentTrackURI | "https://cf-media.sndcdn.com/5j1whqgsum5Q.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNWoxd2hxZ3N1bTVRLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzEwNjk2ODR9fX1dfQ__&Signature=EO0I6Z2cY5E2I9nV3Q45JZaHv6Aqrecj6mwXaAKR~dq1FoGcRrWHF4SwGnXScZnRkKnFWsmMcS8h~ayAoRQZSo50B2uU3mvyFZtV1uZJaTRnPmRqMHCavaZdTSX2Rn6yFKP1Ld9A68he8jVjmWu3oWoOouVH6Lx6CvJyV~IarN4voEcBxBZoVt3LtKYRZ3xmp~P60-R8MqaMVWmW0hOCHJ38MaFpsbLU8ptfzCRQGtPGIXSJIxGDPTa62UwIS~wgCBgFCSQyLzF2OxgTiFjK7mTYPtiD5pHjor9Vui6mrqt~LRttEIslMviJdplY4hEgwWcB-UDVuEuxpqT~ZtInhg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ"
rooms |  
0 |  
roomUDN | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
name | "Wohnzimmer"
PowerState | "AUTOMATIC_STANDBY"
online | true
Volume | "58"
Mute | "0"
TransportState | "STOPPED"
udn | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState | "AUTOMATIC_STANDBY"
renderer |  
0 |  
udn | "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name | "Speaker Wohnzimmer"
udn | "uuid:89b3dfaa-f150-4485-84c1-30bc50cac876"
mediaItem |  
class | "object.item.audioItem.musicTrack"
section | "SoundCloud"
name | "Track"
durability | null
childCount | null
parentID | "0/Favorites/RecentlyPlayed"
id | "0/Favorites/RecentlyPlayed/527"
restricted | "1"
refID | "0/SoundCloud/DirectAccess/Track/t618985140"
title | "Haszcara (feat. Tolztoy) Nein"
description | null
artist | "RapidGaming iTnerz"
albumArtURI | "http://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&service=SoundCloud"
genre | null
album | null
date | null
creator | "RapidGaming iTnerz"
originalTrackNumber | null
protocolInfo | "soundcloud-track-href:*:audio/soundcloud-track:*"
duration | "0:02:55.000"
friendlyName | "Wohnzimmer"
host | "192.168.178.20"
manufacturer | "Lautsprecher Teufel GmbH"
modelNumber | "2"
1 |  
InstanceID | 0
AVTransportURIMetaData | ""
CurrentTrackDuration | "NOT_IMPLEMENTED"
PowerState | "AUTOMATIC_STANDBY"
AVTransportURI | ""
CurrentPlayMode | "NORMAL"
TransportState | "NO_MEDIA_PRESENT"
OwnsAudioResource | "0"
CurrentTransportActions | ""
TransportStatus | "OK"
LowDB | "0.000000"
Mute | "0"
MidDB | "0.000000"
Volume | "58"
Balance | "0"
HighDB | "0.000000"
rooms |  
0 |  
name | "Wohnzimmer"
udn | "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState | "AUTOMATIC_STANDBY"
renderer |  
0 |  
udn | "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name | "Speaker Wohnzimmer"
udn | "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
mediaItem | null
friendlyName | "Speaker Wohnzimmer"
host | "192.168.178.20"
manufacturer | "Lautsprecher Teufel GmbH"
modelNumber | "2"

And from this I can leave standby:

requestUrl | "/raumserver/controller/leaveStandby"
-- | --
action | "leaveStandby"
error | false
msg | ""
data |  
result | "[object Object][object Object]"
udn | "uuid:89b3dfaa-f150-4485-84c1-30bc50cac876"

I don't know yet, how to reproduce the error.

**Comment by ChriD** [comment]
Hmm..

Maybe it was because the first time you tried it, the room was not in a zone.
There may be a problem on changing settings on rooms which are "unassigned" (not in a zone)


best regards

________________________________
Von: fschuber <notifications@github.com>
Gesendet: Montag, 14. Oktober 2019 18:00
An: ChriD/node-raumserver <node-raumserver@noreply.github.com>
Cc: Christian <chris_d85@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [ChriD/node-raumserver] Wake up from automatic standby Raumfeld Stero M (#88)


It was the same using ?id="Wohnzimmer".
I think the cause is with the source of the music I play.
I did play some music, so now my automatic_Standby is:


requestUrl      "/raumserver/controller/getRendererState"
action  "getRendererState"
error   false
msg     ""
data
0
Mute    0
InstanceID      0
RoomVolumes     "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=58"
Volume  "58"
RoomMutes       "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=0"
CurrentTrackMetaData    "\n<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:raumfeld="urn:schemas-raumfeld-com:meta-data/raumfeld" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dc="http://purl.org/dc/elements/1.1/\<http://purl.org/dc/elements/1.1/%5C>" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:pv="http://www.pv.com/pvns/\<http://www.pv.com/pvns/%5C>" lang="en">\n <item parentID="0/Favorites/RecentlyPlayed" id="0/Favorites/RecentlyPlayed/527" restricted="1" refID="0/SoundCloud/DirectAccess/Track/t618985140">\n raumfeld:nameTrack</raumfeld:name>\n upnp:classobject.item.audioItem.musicTrack</upnp:class>\n raumfeld:sectionSoundCloud</raumfeld:section>\n dc:titleHaszcara (feat. Tolztoy) Nein</dc:title>\n <upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&amp;service=SoundCloud</upnp:albumArtURI>\n <res protocolInfo="soundcloud-track-href::audio/soundcloud-track:" duration="0:02:55.000">https://api-partners.soundcloud.com/tracks/soundcloud:tracks:618985140/play?anonymous_id=12a3415a-b765-4a7d-98d4-38ce923eacc6&amp;client_id=3f1da551d8578cf5985a97655011c482\n upnp:artistRapidGaming iTnerz</upnp:artist>\n dc:creatorRapidGaming iTnerz</dc:creator>\n raumfeld:likedOnMusicServicefalse</raumfeld:likedOnMusicService>\n \n\n"
CurrentRecordQualityMode        "NOT_IMPLEMENTED"
AbsoluteTimePosition    "00:00:00"
SecondsUntilSleep       "0"
CurrentTrack    "1"
AVTransportURIMetaData  "\n<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/\<http://purl.org/dc/elements/1.1/%5C>" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:raumfeld="urn:schemas-raumfeld-com:meta-data/raumfeld" xmlns:pv="http://www.pv.com/pvns/\"><http://www.pv.com/pvns/%5C%22%3E><item parentID="0/Favorites/RecentlyPlayed" refID="0/SoundCloud/DirectAccess/Track/t618985140" id="0/Favorites/RecentlyPlayed/527" restricted="1">raumfeld:sectionSoundCloud</raumfeld:section>dc:titleHaszcara (feat. Tolztoy) Nein</dc:title>upnp:albumArtURIhttp://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&amp;service=SoundCloud</upnp:albumArtURI>raumfeld:nameTrack</raumfeld:name>upnp:classobject.item.audioItem.musicTrack</upnp:class>upnp:artistRapidGaming iTnerz</upnp:artist>raumfeld:duration175</raumfeld:duration>\n"
PossiblePlaybackStorageMedia    "NETWORK"
TransportPlaySpeed      "1"
CurrentTrackDuration    "00:02:55"
PossibleRecordQualityModes      "NOT_IMPLEMENTED"
Bitrate "128"
PossibleRecordStorageMedia      "NONE"
AVTransportURI  "dlna-playsingle://uuid%3A63d8bd10-ce01-4113-823c-49897c0eacc7?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&iid=0%2FFavorites%2FRecentlyPlayed%2F527"
RelativeTimePosition    "00:00:00"
RelativeCounterPosition "1"
CurrentPlayMode "NORMAL"
TransportState  "STOPPED"
AbsoluteCounterPosition "1"
CurrentTransportActions "Play,Previous,Repeat,Seek"
RoomStates      "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9=STOPPED"
ContentType     "MP3"
NumberOfTracks  "1"
SleepTimerActive        "0"
TransportStatus "OK"
CurrentTrackURI "https://cf-media.sndcdn.com/5j1whqgsum5Q.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNWoxd2hxZ3N1bTVRLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzEwNjk2ODR9fX1dfQ__&Signature=EO0I6Z2cY5E2I9nV3Q45JZaHv6Aqrecj6mwXaAKR~dq1FoGcRrWHF4SwGnXScZnRkKnFWsmMcS8h~ayAoRQZSo50B2uU3mvyFZtV1uZJaTRnPmRqMHCavaZdTSX2Rn6yFKP1Ld9A68he8jVjmWu3oWoOouVH6Lx6CvJyV~IarN4voEcBxBZoVt3LtKYRZ3xmp~P60-R8MqaMVWmW0hOCHJ38MaFpsbLU8ptfzCRQGtPGIXSJIxGDPTa62UwIS~wgCBgFCSQyLzF2OxgTiFjK7mTYPtiD5pHjor9Vui6mrqt~LRttEIslMviJdplY4hEgwWcB-UDVuEuxpqT~ZtInhg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ"
rooms
0
roomUDN "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
name    "Wohnzimmer"
PowerState      "AUTOMATIC_STANDBY"
online  true
Volume  "58"
Mute    "0"
TransportState  "STOPPED"
udn     "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState      "AUTOMATIC_STANDBY"
renderer
0
udn     "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name    "Speaker Wohnzimmer"
udn     "uuid:89b3dfaa-f150-4485-84c1-30bc50cac876"
mediaItem
class   "object.item.audioItem.musicTrack"
section "SoundCloud"
name    "Track"
durability      null
childCount      null
parentID        "0/Favorites/RecentlyPlayed"
id      "0/Favorites/RecentlyPlayed/527"
restricted      "1"
refID   "0/SoundCloud/DirectAccess/Track/t618985140"
title   "Haszcara (feat. Tolztoy) Nein"
description     null
artist  "RapidGaming iTnerz"
albumArtURI     "http://192.168.178.20:47366/raumfeldImage?playlistId=https%3A%2F%2Fi1.sndcdn.com%2Fartworks-000533239329-wkir97-large.jpg&service=SoundCloud"
genre   null
album   null
date    null
creator "RapidGaming iTnerz"
originalTrackNumber     null
protocolInfo    "soundcloud-track-href::audio/soundcloud-track:"
duration        "0:02:55.000"
friendlyName    "Wohnzimmer"
host    "192.168.178.20"
manufacturer    "Lautsprecher Teufel GmbH"
modelNumber     "2"
1
InstanceID      0
AVTransportURIMetaData  ""
CurrentTrackDuration    "NOT_IMPLEMENTED"
PowerState      "AUTOMATIC_STANDBY"
AVTransportURI  ""
CurrentPlayMode "NORMAL"
TransportState  "NO_MEDIA_PRESENT"
OwnsAudioResource       "0"
CurrentTransportActions ""
TransportStatus "OK"
LowDB   "0.000000"
Mute    "0"
MidDB   "0.000000"
Volume  "58"
Balance "0"
HighDB  "0.000000"
rooms
0
name    "Wohnzimmer"
udn     "uuid:ad0a9f84-97e3-41ea-b330-45231b30dbd9"
powerState      "AUTOMATIC_STANDBY"
renderer
0
udn     "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
name    "Speaker Wohnzimmer"
udn     "uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d"
mediaItem       null
friendlyName    "Speaker Wohnzimmer"
host    "192.168.178.20"
manufacturer    "Lautsprecher Teufel GmbH"
modelNumber     "2"

And from this I can leave standby:

requestUrl      "/raumserver/controller/leaveStandby"
action  "leaveStandby"
error   false
msg     ""
data
result  "[object Object][object Object]"
udn     "uuid:89b3dfaa-f150-4485-84c1-30bc50cac876"

I don't know yet, how to reproduce the error.

**Comment by fschuber** [comment]
No change in the room settings. It did work before.

Log file:

more app.2019-10-12-1822.log

2019-10-12T18:22:46.935Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-12T18:22:46.942Z - error: [Raumserver] Request was rejected:  errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-12T18:22:47.627Z - error: [Request.setVolume] VirtualMediaRenderer for id 'Wohnzimmer' not found
2019-10-12T18:22:47.630Z - error: [Request.setVolume] Some renderers had exceptions:  message=VirtualMediaRenderer for id 'Wohnzimmer' not found, stack=Error: VirtualMediaRenderer for id 'Wohnzimmer' not found
    at Request_SetVolume.run (/etc/raumserver/node_modules/node-raumserver/lib/lib.base.requestMediaRenderer.js:95:27)
    at Raumserver.handleRequestObject (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:153:28)
    at Raumserver.requestReceived (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:115:22)
    at Server.<anonymous> (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:84:26)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
2019-10-12T18:22:47.633Z - error: [Raumserver] Request was rejected:  errorMessage=Error: VirtualMediaRenderer for id 'Wohnzimmer' not found, errorData=null
2019-10-12T18:22:48.512Z - info: [DeviceManager] Raumfeld Media renderer added: Speaker Wohnzimmer (uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d)
2019-10-12T18:22:52.161Z - info: [DeviceManager] Virtual media renderer added: Wohnzimmer (uuid:ae100d56-dd3e-4e1e-94d7-05445f100705)
2019-10-12T18:22:56.623Z - info: [DeviceManager] Raumfeld media server added: Raumfeld MediaServer (uuid:63d8bd10-ce01-4113-823c-49897c0eacc7)

Then they all go like this:

more app.2019-10-14-1605.log
2019-10-14T16:05:02.993Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-14T16:05:02.997Z - error: [Raumserver] Request was rejected:  errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-14T16:05:11.546Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-14T16:05:11.548Z - error: [Raumserver] Request was rejected:  errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-14T16:05:12.336Z - info: [DeviceManager] Virtual media renderer added: Wohnzimmer (uuid:89b3dfaa-f150-4485-84c1-30bc50cac876)

**Comment by ChriD** [comment]
Those 2 logs say that the media server and renderers were found 6 seconds after you did the request.
What is your setup? Where is the node-raumserver installed?

________________________________
Von: fschuber <notifications@github.com>
Gesendet: Montag, 14. Oktober 2019 19:08
An: ChriD/node-raumserver <node-raumserver@noreply.github.com>
Cc: Christian <chris_d85@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [ChriD/node-raumserver] Wake up from automatic standby Raumfeld Stero M (#88)


No change in the room settings. It did work before.

Log file:

more app.2019-10-12-1822.log

2019-10-12T18:22:46.935Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-12T18:22:46.942Z - error: [Raumserver] Request was rejected: errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-12T18:22:47.627Z - error: [Request.setVolume] VirtualMediaRenderer for id 'Wohnzimmer' not found
2019-10-12T18:22:47.630Z - error: [Request.setVolume] Some renderers had exceptions: message=VirtualMediaRenderer for id 'Wohnzimmer' not found, stack=Error: VirtualMediaRenderer for id 'Wohnzimmer' not found
at Request_SetVolume.run (/etc/raumserver/node_modules/node-raumserver/lib/lib.base.requestMediaRenderer.js:95:27)
at Raumserver.handleRequestObject (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:153:28)
at Raumserver.requestReceived (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:115:22)
at Server. (/etc/raumserver/node_modules/node-raumserver/lib/lib.raumserver.js:84:26)
at emitTwo (events.js:126:13)
at Server.emit (events.js:214:7)
at parserOnIncoming (_http_server.js:619:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
2019-10-12T18:22:47.633Z - error: [Raumserver] Request was rejected: errorMessage=Error: VirtualMediaRenderer for id 'Wohnzimmer' not found, errorData=null
2019-10-12T18:22:48.512Z - info: [DeviceManager] Raumfeld Media renderer added: Speaker Wohnzimmer (uuid:f331bf0c-91ae-4f8b-a599-e2aa8874e23d)
2019-10-12T18:22:52.161Z - info: [DeviceManager] Virtual media renderer added: Wohnzimmer (uuid:ae100d56-dd3e-4e1e-94d7-05445f100705)
2019-10-12T18:22:56.623Z - info: [DeviceManager] Raumfeld media server added: Raumfeld MediaServer (uuid:63d8bd10-ce01-4113-823c-49897c0eacc7)

Then they all go like this:

more app.2019-10-14-1605.log
2019-10-14T16:05:02.993Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-14T16:05:02.997Z - error: [Raumserver] Request was rejected: errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-14T16:05:11.546Z - error: [Request.getRendererState] Media Renderer for id 'Wohnzimmer' not found
2019-10-14T16:05:11.548Z - error: [Raumserver] Request was rejected: errorMessage=Error: Media Renderer for id 'Wohnzimmer' not found, errorData=null
2019-10-14T16:05:12.336Z - info: [DeviceManager] Virtual media renderer added: Wohnzimmer (uuid:89b3dfaa-f150-4485-84c1-30bc50cac876)

**Comment by fschuber** [comment]
I'm streaming music from a western digital MyCloud with twonky music server. This MyCloud is buggy and drops out of the network every few days. I suspect this behaviour to be the cause.
Today when I came home, the speakers did not react via raumserver (and the MyCloud is down). First log entry of today:

2019-10-16T15:52:19.155Z - warn: [DeviceManager] Virtual media renderer removed:
 Wohnzimmer
2019-10-16T15:52:19.180Z - error: [MediaRenderer|Wohnzimmer] Error: connect ECON
NREFUSED 192.168.178.20:57786
2019-10-16T15:52:19.181Z - error: [MediaRenderer|Wohnzimmer] Error: connect ECON
NREFUSED 192.168.178.20:57786
2019-10-16T15:52:21.666Z - warn: [MediaDataConverter] Unhandled media item type:
 object.item.audioitem.audiobroadcast id=0/GoogleCast/Track, parentID=0/GoogleCa
st, restricted=0, upnp:class=[object.item.audioItem.audioBroadcast], raumfeld:se
ction=[GoogleCast], res=[_=google-cast://, protocolInfo=google-cast:*:audio/goog
le-cast-track:*]

When I use the raumfeld app to select a different music source, e.g. chromecast or tunIn, all will be back to proper operation. (The MyCloud needs to be powered off and on).
