### ISSUE TITLE
Error: message=Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by julvei** [ChriD/node-raumserver#91]
Hi ChriD (or other developers),

when I setup the server I get following error after it already found all of my devices in the network:

``error: [MediaDataConverter] Error converting media item: {"$":{"restricted":"1"}} message=Cannot read property 'toLowerCase' of null, stack=TypeError: Cannot read property 'toLowerCase' of null``
``at Raumkernel.convertContainer (/home/openhabian/Documents/node/raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:110:33)``
``at /home/openhabian/Documents/node/raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:71:65``
``at Parser.<anonymous> (/home/openhabian/Documents/node/raumserver/node_modules/xml2js/lib/parser.js:304:18)``
``at emitOne (events.js:116:13)``
``at Parser.emit (events.js:211:7)``
``at SAXParser.onclosetag (/home/openhabian/Documents/node/raumserver/node_modules/xml2js/lib/parser.js:262:26)``
``at emit (/home/openhabian/Documents/node/raumserver/node_modules/sax/lib/sax.js:639:35)``
``at emitNode (/home/openhabian/Documents/node/raumserver/node_modules/sax/lib/sax.js:644:5)``
``at closeTag (/home/openhabian/Documents/node/raumserver/node_modules/sax/lib/sax.js:903:7)``
``at SAXParser.write (/home/openhabian/Documents/node/raumserver/node_modules/sax/lib/sax.js:1436:13)``
``at Parser.exports.Parser.Parser.parseString (/home/openhabian/Documents/node/raumserver/node_modules/xml2js/lib/parser.js:323:31)``
``at Parser.parseString (/home/openhabian/Documents/node/raumserver/node_modules/xml2js/lib/parser.js:5:59)``
``at exports.parseString (/home/openhabian/Documents/node/raumserver/node_modules/xml2js/lib/parser.js:369:19)``
``at /home/openhabian/Documents/node/raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:25:13``
``at new Promise (<anonymous>)``
``at Raumkernel.convertXMLToMediaList (/home/openhabian/Documents/node/raumserver/node_modules/node-raumkernel/lib/lib.mediaDataConverter.js:22:16)``

Unfortunately I am a completely new to JavaScript, so I don't know, if this is a problem on my machine or of the stack and how I can fix it. I would appreciate some help or a direction where to dig for a solution.

Thanks a lot!

**Comment by ChriD** [comment]
Hmm... The raumserver tries to parse the media information on the virtual zone renderers. It seems that there is some kind of media item which has no available data (it' data seems to be restricted). Do you use spotify?

**Comment by erikp152** [comment]
@ChriD  i have the same issue spaming my log every 30 seconds. I am using spotify premium. Is there sth we can Do? Seems like there is any null value in a property which is not expected.

**Comment by ChriD** [comment]
Well i can check the var, but as i can see, no media info will be there for spotify things
